-- MySQL Script generated by MySQL Workbench
-- Tue Sep 17 10:04:49 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema isaui
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `isaui` ;

-- -----------------------------------------------------
-- Schema isaui
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `isaui` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
SHOW WARNINGS;
USE `isaui` ;

-- -----------------------------------------------------
-- Table `Carreras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Carreras` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Carreras` (
  `id_carreras` INT NOT NULL AUTO_INCREMENT,
  `nombre_carrera` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_carreras`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Persona` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Persona` (
  `id_persona` INT NOT NULL AUTO_INCREMENT,
  `apellido` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `dni` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `domicilio` VARCHAR(45) NOT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `instagram` VARCHAR(45) NOT NULL,
  `id_carrera` INT NOT NULL,
  PRIMARY KEY (`id_persona`)
  FOREIGN KEY (`id_carreras`) references Carreras(`id_carrera`)
  )
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
